#!/bin/bash

# Generic config builder, recursive edition
# Sorts entries by the basename, regardless of path, and then combines them.
# DANGER: THIS SCRIPT FOLLOW SYMLINKS!
# Example: update-config-deep /etc/make.conf /etc/make.conf.d conf

# Example tree in order it would be combined:
# /etc/make.conf.d/stock/00aaa
# /etc/make.conf.d/host/10aaa
# /etc/make.conf.d/stock/20aaa

FILE=$1
DIR=$2
EXT=$3

usage () {
    echo ""
    echo "Usage:"
    echo " update-config-deep /etc/make.conf /etc/make.conf.d conf"
    exit 1
}

if [ -z "$FILE" ] ; then
    echo "No file given!"
    usage
fi

if [ -z "$DIR" ] ; then
    echo "No directory given!"
    usage
fi

if [ -z "$EXT" ] ; then
    echo "No extension given!"
    usage
fi

if [ -d $DIR ]; then
    if [ -f $FILE ] ; then
        cp $FILE $FILE~
    fi
    find $DIR -type f -follow -printf '%f %p\n' | \
        sort | \
        awk '{print $2}' | \
        xargs cat >$FILE
else
    echo "No $DIR directory found!"
    exit 1
fi
