#!/bin/bash

# Generic config builder
# Example: update-config /etc/make.conf /etc/make.conf.d conf

FILE=$1
DIR=$2
EXT=$3

usage () {
    echo ""
    echo "Usage:"
    echo " update-config /etc/make.conf /etc/make.conf.d conf"
    exit 1
}

if [ -z "$FILE" ] ; then
    echo "No file given!"
    usage
fi

if [ -z "$DIR" ] ; then
    echo "No directory given!"
    usage
fi

if [ -z "$EXT" ] ; then
    echo "No extension given!"
    usage
fi

if [ -d $DIR ]; then
    if [ -f $FILE ] ; then
        cp $FILE $FILE~
    fi
    cat $DIR/*.$EXT > $FILE
else
    echo "No $DIR directory found!"
    exit 1
fi
